cmake_minimum_required (VERSION 4.0.0)
project (210-labs)

set(CXX_STANDARD C++23)
set(CXX_STANDARD_REQUIRED ON)
set(CXX_EXTENSIONS OFF)

add_subdirectory(lab-1)
add_subdirectory(lab-2)
add_subdirectory(lab-3)
add_subdirectory(lab-4)
add_subdirectory(lab-7)
add_subdirectory(lab-9)
add_subdirectory(lab-11)
add_subdirectory(lab-13)

# (O.O)
